// core/action-types.js
export const ActionTypes = {
  // Game flow actions (need sync)
  PLAY_CARD: "PLAY_CARD",
  USE_ABILITY: "USE_ABILITY",
  USE_CAMP_ABILITY: "USE_CAMP_ABILITY",
  JUNK_CARD: "JUNK_CARD",
  DRAW_CARD: "DRAW_CARD",
  END_TURN: "END_TURN",
  TAKE_WATER_SILO: "TAKE_WATER_SILO",
  SELECT_TARGET: "SELECT_TARGET",

  // Synchronization actions
  SYNC_PHASE_CHANGE: "SYNC_PHASE_CHANGE",
  SYNC_CAMP_SELECTION: "SYNC_CAMP_SELECTION",
  SYNC_CAMP_DISTRIBUTION: "SYNC_CAMP_DISTRIBUTION",
  SYNC_EVENT_QUEUE: "SYNC_EVENT_QUEUE",
  SYNC_PENDING_STATE: "SYNC_PENDING_STATE",
  SYNC_REPLENISH_COMPLETE: "SYNC_REPLENISH_COMPLETE",

  // New sync actions we need
  PLAYER_DREW_CARD: "PLAYER_DREW_CARD",
  CARD_PLAYED: "CARD_PLAYED",
  ABILITY_USED: "ABILITY_USED",
  CARD_JUNKED: "CARD_JUNKED",

  // Camp selection
  START_CAMP_SELECTION: "START_CAMP_SELECTION",
  SELECT_CAMP: "SELECT_CAMP",
  DESELECT_CAMP: "DESELECT_CAMP",
  CONFIRM_CAMPS: "CONFIRM_CAMPS",
  FINALIZE_CAMPS: "FINALIZE_CAMPS",
};
