// core/action-types.js
export const ActionTypes = {
  PLAY_CARD: "PLAY_CARD",
  USE_ABILITY: "USE_ABILITY",
  USE_CAMP_ABILITY: "USE_CAMP_ABILITY",
  JUNK_CARD: "JUNK_CARD",
  DRAW_CARD: "DRAW_CARD",
  END_TURN: "END_TURN",
  TAKE_WATER_SILO: "TAKE_WATER_SILO",
  SELECT_TARGET: "SELECT_TARGET",
  // Camp selection actions
  START_CAMP_SELECTION: "START_CAMP_SELECTION",
  SELECT_CAMP: "SELECT_CAMP",
  DESELECT_CAMP: "DESELECT_CAMP",
  CONFIRM_CAMPS: "CONFIRM_CAMPS",
  SYNC_CAMP_SELECTION: "SYNC_CAMP_SELECTION",
  SYNC_CAMP_DISTRIBUTION: "SYNC_CAMP_DISTRIBUTION",
  FINALIZE_CAMPS: "FINALIZE_CAMPS",
};
