// core/action-types.js
export const ActionTypes = {
  PLAY_CARD: "PLAY_CARD",
  USE_ABILITY: "USE_ABILITY",
  USE_CAMP_ABILITY: "USE_CAMP_ABILITY",
  JUNK_CARD: "JUNK_CARD",
  DRAW_CARD: "DRAW_CARD",
  END_TURN: "END_TURN",
  TAKE_WATER_SILO: "TAKE_WATER_SILO",
  SELECT_TARGET: "SELECT_TARGET",
};
